// The `systemctl --user` unit that runs Playhook's card watcher inside SteamOS Game Mode, plus the
// systemctl calls that install and remove it. The unit TEXT is built by a pure function (unit-tested);
// only installDaemonUnit/removeDaemonUnit touch the filesystem and spawn systemctl.
//
// Two decisions worth keeping in view:
//
//  - **Bound to `gamescope-session.target`, not `default.target`.** That target exists on stock SteamOS
//    (verified on a Deck: `systemctl --user list-units --type=target` lists it, and `ps` shows
//    `systemctl --user --wait start gamescope-session.target` bringing it up). Binding to it means systemd
//    itself starts the daemon on entering Game Mode and stops it on leaving — so the daemon needs no
//    mode check of its own. It could not do one anyway: a unit's environment has neither `SteamOS` nor
//    `SteamGamepadUI` (nor even DISPLAY), so isGamescopeSession() would read false inside it.
//
//  - **`ELECTRON_RUN_AS_NODE=1` is mandatory, not an optimisation.** Under systemd in Game Mode a normal
//    Electron start dies with "Missing X server or $DISPLAY" — the unit environment has no display at all
//    (verified). Running the same binary as plain Node avoids Chromium entirely, which is legitimate
//    because everything the daemon touches (drive-watcher, platform/, shared/) is electron-free.
import path from 'node:path';
import fs from 'node:fs/promises';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { log } from './logger';

const execFileAsync = promisify(execFile);

export const DAEMON_UNIT_NAME = 'playhook-daemon.service';

/** Where the compiled daemon entry point sits INSIDE the asar (`files: dist/**` keeps the dist/ prefix). */
export const DAEMON_ENTRY_IN_ASAR = ['app.asar', 'dist', 'main', 'daemon.js'] as const;

export function daemonUnitPath(home: string): string {
  return path.posix.join(home, '.config', 'systemd', 'user', DAEMON_UNIT_NAME);
}

/**
 * The `ExecStart` command. It must be self-contained and resolve everything at RUNTIME: an AppImage is
 * mounted at `/tmp/.mount_Playho<random>`, and that suffix changes on every launch (observed NJoZ6K,
 * SUAM0k, qV6y7T) — so no path INTO the AppImage may ever be baked into the unit or saved to config.
 * `process.resourcesPath` is defined even under ELECTRON_RUN_AS_NODE (verified on a Deck), which is what
 * makes this one-liner possible.
 */
export function daemonExecStart(appImagePath: string): string {
  const entry = DAEMON_ENTRY_IN_ASAR.map((segment) => `'${segment}'`).join(',');
  return `${appImagePath} -e "require(require('path').join(process.resourcesPath,${entry}))"`;
}

/**
 * The unit file contents. `Restart=on-failure` (not `always`) plus the StartLimit pair so a daemon that
 * crashes on startup gives up instead of spinning forever.
 */
export function buildDaemonUnit(appImagePath: string): string {
  return [
    '# Generated by Playhook — do not edit; it is rewritten on every start.',
    '[Unit]',
    'Description=Playhook card watcher (Game Mode)',
    'PartOf=gamescope-session.target',
    '',
    '[Service]',
    'Type=simple',
    'Environment=ELECTRON_RUN_AS_NODE=1',
    `ExecStart=${daemonExecStart(appImagePath)}`,
    'Restart=on-failure',
    'RestartSec=5',
    'StartLimitIntervalSec=60',
    'StartLimitBurst=3',
    '',
    '[Install]',
    'WantedBy=gamescope-session.target',
    '',
  ].join('\n');
}

/** Runs `systemctl --user …`, resolving to false (with a breadcrumb) instead of throwing. */
async function systemctl(...args: readonly string[]): Promise<boolean> {
  try {
    await execFileAsync('systemctl', ['--user', ...args]);
    return true;
  } catch (cause) {
    log.warn(
      `[daemon-unit] systemctl --user ${args.join(' ')} failed:`,
      cause instanceof Error ? cause.message : String(cause),
    );
    return false;
  }
}

/**
 * Writes the unit and enables it. Idempotent and cheap, so it runs on every Desktop Mode start: an
 * electron-updater in-place update can change `$APPIMAGE`, and a unit pointing at the old path would
 * simply stop working, silently.
 *
 * `enable --now` (not bare `enable`) matters: `enable` only creates the symlink, so "press the tray item,
 * then go straight to Game Mode" would not work until the next login. `try-restart` picks up a new binary
 * path when the unit was regenerated after an update — without it the OLD process keeps running.
 */
export async function installDaemonUnit(home: string, appImagePath: string): Promise<boolean> {
  const unitPath = daemonUnitPath(home);
  const contents = buildDaemonUnit(appImagePath);
  try {
    await fs.mkdir(path.posix.dirname(unitPath), { recursive: true });
    const existing = await fs.readFile(unitPath, 'utf8').catch(() => null);
    if (existing === contents) {
      // Unchanged: still make sure it is enabled and running the current binary, but skip the write.
      await systemctl('enable', '--now', DAEMON_UNIT_NAME);
      return true;
    }
    await fs.writeFile(unitPath, contents, 'utf8');
    log.info(`[daemon-unit] wrote "${unitPath}"`);
  } catch (cause) {
    log.error(
      '[daemon-unit] could not write the unit:',
      cause instanceof Error ? cause.message : String(cause),
    );
    return false;
  }
  await systemctl('daemon-reload');
  const enabled = await systemctl('enable', '--now', DAEMON_UNIT_NAME);
  await systemctl('try-restart', DAEMON_UNIT_NAME);
  return enabled;
}

/** Stops, disables and deletes the unit. Best-effort: a missing unit is success, not an error. */
export async function removeDaemonUnit(home: string): Promise<void> {
  await systemctl('disable', '--now', DAEMON_UNIT_NAME);
  try {
    await fs.rm(daemonUnitPath(home), { force: true });
  } catch (cause) {
    log.warn(
      '[daemon-unit] could not delete the unit:',
      cause instanceof Error ? cause.message : String(cause),
    );
  }
  await systemctl('daemon-reload');
}
