// electron-builder afterPack hook (Linux only): replaces the packed executable with a small launcher
// script that injects `--no-sandbox` when the app starts inside a SteamOS Game Mode (gamescope) session.
//
// Why a wrapper and not app.commandLine.appendSwitch('no-sandbox'): sandbox switches are consumed while
// Chromium boots, BEFORE the main script runs, so appendSwitch is silently ignored — the flag has to be on
// the real argv. And why not electron-builder's `linux.executableArgs`: that only lands in the generated
// .desktop `Exec=` line, which Steam bypasses — it runs the AppImage binary directly.
//
// Why the AppImage's own AppRun doesn't cover it: AppRun probes `unshare -Ur true` and adds --no-sandbox
// only when unprivileged user namespaces are unavailable. SteamOS HAS them, so the probe succeeds and the
// flag is withheld — yet the renderer still fails to start under gamescope. That heuristic is simply wrong
// for Game Mode, so we decide it ourselves, one layer below AppRun (which execs this script as $BIN).
import { rename, writeFile } from 'node:fs/promises';
import path from 'node:path';

/**
 * The launcher script. Mirrors isGamescopeSession() (src/main/gamescope.ts) — keep the two in sync; the
 * TS one drives the UX model, this one only decides the sandbox flag. Outside Game Mode (desktop Linux,
 * KDE) nothing is added, so the sandbox stays on where it actually works.
 */
function launcherScript(realBinary) {
  return `#!/usr/bin/env bash
# Generated by scripts/after-pack.mjs — do not edit inside the package.
# Injects --no-sandbox in a SteamOS Game Mode (gamescope) session, where Chromium's sandbox cannot start
# the renderer. Everywhere else the app runs with the sandbox intact.
set -e

HERE="$(dirname "$(readlink -f "\${0}")")"
BIN="\${HERE}/${realBinary}"

# ELECTRON_RUN_AS_NODE turns the binary into plain Node, which does not know --no-sandbox and exits with
# "bad option". That mode is how the Game Mode daemon runs (systemd has no display), so the flag must be
# withheld there. GUI launches are unaffected.
if [ -n "\${ELECTRON_RUN_AS_NODE:-}" ] ; then
  exec "\${BIN}" "$@"
fi

# Already passed by AppRun's own probe, by Steam launch options or by the user → never duplicate it.
for arg in "$@" ; do
  if [ "\${arg}" = "--no-sandbox" ] ; then
    exec "\${BIN}" "$@"
  fi
done

# Mirror of isGamescopeSession(): Steam's env pair for Game Mode processes, or the compositor's own id.
XDG_LOWER="$(printf '%s' "\${XDG_CURRENT_DESKTOP:-}" | tr '[:upper:]' '[:lower:]')"
if { [ "\${SteamOS:-}" = "1" ] && [ "\${SteamGamepadUI:-}" = "1" ] ; } || [ "\${XDG_LOWER}" = "gamescope" ] ; then
  exec "\${BIN}" --no-sandbox "$@"
fi

exec "\${BIN}" "$@"
`;
}

export default async function afterPack(context) {
  if (context.electronPlatformName !== 'linux') return;

  // Ask the packager for the executable name instead of guessing it from productName/name.
  const executable = context.packager.executableName;
  const realBinary = `${executable}.bin`;
  const dir = context.appOutDir;

  await rename(path.join(dir, executable), path.join(dir, realBinary));
  await writeFile(path.join(dir, executable), launcherScript(realBinary), { mode: 0o755 });

  console.log(`  • gamescope launcher wrapper written  executable=${executable} real=${realBinary}`);
}
