// electron-builder afterPack hook (Linux only): replaces the packed executable with a small launcher
// script that puts two Chromium flags on the real argv — `--no-sandbox` inside a SteamOS Game Mode
// (gamescope) session, and `--xdg-portal-required-version=4` everywhere (see the script for each).
//
// Why a wrapper and not app.commandLine.appendSwitch: both flags are consumed while Chromium boots, BEFORE
// the main script runs, so appendSwitch is silently ignored — they have to be on the real argv. And why not
// electron-builder's `linux.executableArgs`: that only lands in the generated .desktop `Exec=` line, which
// Steam bypasses — it runs the AppImage binary directly.
//
// Why the AppImage's own AppRun doesn't cover the sandbox: AppRun probes `unshare -Ur true` and adds
// --no-sandbox only when unprivileged user namespaces are unavailable. SteamOS HAS them, so the probe
// succeeds and the flag is withheld — yet the renderer still fails to start under gamescope. That heuristic
// is simply wrong for Game Mode, so we decide it ourselves, one layer below AppRun (which execs this
// script as $BIN).
import { rename, writeFile } from 'node:fs/promises';
import path from 'node:path';

/**
 * The launcher script. Mirrors isGamescopeSession() (src/main/gamescope.ts) — keep the two in sync; the
 * TS one drives the UX model, this one only decides the sandbox flag. Outside Game Mode (desktop Linux,
 * KDE) the sandbox is left on, since it works there.
 */
function launcherScript(realBinary) {
  return `#!/usr/bin/env bash
# Generated by scripts/after-pack.mjs — do not edit inside the package.
# Puts the two flags that must be on the REAL argv (Chromium reads both before the main script runs) in
# front of everything the caller passes.
set -e

HERE="$(dirname "$(readlink -f "\${0}")")"
BIN="\${HERE}/${realBinary}"

FLAGS=()

# Configure's folder pickers pass a defaultPath (open in the game's Wine prefix). Through the XDG portal
# that is unreachable by design: the FileChooser spec calls the start folder a suggestion implementations
# "are free to ignore", and KDE's does — on the Deck (portal FileChooser v4, checked on hardware) the
# picker always opened at $HOME. Chromium only uses the portal when its version >= this threshold, so an unreachable
# number pins it to the GTK/KDE dialog, which honours the path. Safe here: an AppImage isn't sandboxed, so
# a native dialog reads the disk fine — the portal buys us nothing.
if ! printf '%s\\n' "$@" | grep -q '^--xdg-portal-required-version' ; then
  FLAGS+=(--xdg-portal-required-version=999)
fi

# Chromium's sandbox can't start the renderer inside a gamescope (Game Mode) session. Mirror of
# isGamescopeSession(): Steam's env pair for Game Mode processes, or the compositor's own id. Skipped when
# the caller already passed the flag (AppRun's own probe, Steam launch options) → never duplicated.
XDG_LOWER="$(printf '%s' "\${XDG_CURRENT_DESKTOP:-}" | tr '[:upper:]' '[:lower:]')"
if { [ "\${SteamOS:-}" = "1" ] && [ "\${SteamGamepadUI:-}" = "1" ] ; } || [ "\${XDG_LOWER}" = "gamescope" ] ; then
  if ! printf '%s\\n' "$@" | grep -qx -- '--no-sandbox' ; then
    FLAGS+=(--no-sandbox)
  fi
fi

exec "\${BIN}" "\${FLAGS[@]}" "$@"
`;
}

export default async function afterPack(context) {
  if (context.electronPlatformName !== 'linux') return;

  // Ask the packager for the executable name instead of guessing it from productName/name.
  const executable = context.packager.executableName;
  const realBinary = `${executable}.bin`;
  const dir = context.appOutDir;

  await rename(path.join(dir, executable), path.join(dir, realBinary));
  await writeFile(path.join(dir, executable), launcherScript(realBinary), { mode: 0o755 });

  console.log(`  • gamescope launcher wrapper written  executable=${executable} real=${realBinary}`);
}
