/**
 * The Library grid's artwork cache: a bounded LRU in front of `library:grid-request`, with a queue in
 * front of the IPC.
 *
 * Both bounds exist for the same reason. A cover is generated by MAIN on the first request — decode,
 * resize, encode, write (see LibraryStore.readGridThumb) — synchronously, on the very process that also
 * serves every other IPC call of the launcher. The grid's window is up to ~54 cards, so a cold library
 * would fire ~54 of those at once and stall main; and holding every cover a scroll ever touched would
 * grow without limit on a library of hundreds. Hence: at most `concurrency` requests in flight, LIFO so
 * the cards nearest the selection (queued last) are served first, and the oldest decoded URLs dropped.
 *
 * The carousel keeps its own, unbounded cache on purpose — its row holds ~40 entries at most and it works
 * (see carousel.ts). This one is the library's alone.
 */
import type { LibraryEntry } from '../shared/types.js';

export interface CardArtDeps {
  requestGrid(id: string): Promise<string | null>;
}

export interface CardArtCache {
  /** The cover, `null` when the game has none, `undefined` when it was never loaded (or was evicted). */
  get(key: string): string | null | undefined;
  /** Claims the slot and asks for the cover through the queue; resolves null when there is none. */
  load(key: string, id: string): Promise<string | null>;
  /** Drops the queued-but-not-yet-started requests whose keys are not in `keep`. */
  dropPending(keep: ReadonlySet<string>): void;
  /** Keys the LRU threw out — the host clears their background-image. Exactly one subscriber. */
  onEvict(handler: (key: string) => void): void;
}

/**
 * How many decoded covers are held at once. Comfortably above the artwork window (~9 rows), so walking a
 * row back and forth never re-requests, while a library of hundreds still has a ceiling.
 */
export const ART_CAPACITY = 120;

/** How many covers main is asked for at once — it generates them synchronously (see the module note). */
export const ART_CONCURRENCY = 3;

/** Cache key of one game's artwork: the id, plus the revision that changes when main re-copies it. */
export function artKey(game: LibraryEntry): string {
  return `${game.id}@${game.artRev ?? ''}`;
}

interface PendingRequest {
  readonly id: string;
  readonly promise: Promise<string | null>;
  readonly settle: (url: string | null) => void;
  started: boolean;
}

export function createCardArtCache(
  deps: CardArtDeps,
  capacity = ART_CAPACITY,
  concurrency = ART_CONCURRENCY,
): CardArtCache {
  const entries = new Map<string, string | null>();
  const pending = new Map<string, PendingRequest>();
  const queue: string[] = [];
  let inFlight = 0;
  let evicted: (key: string) => void = () => {};

  function touch(key: string, value: string | null): void {
    entries.delete(key);
    entries.set(key, value);
    while (entries.size > capacity) {
      const oldest = entries.keys().next();
      if (oldest.done === true) break;
      entries.delete(oldest.value);
      evicted(oldest.value);
    }
  }

  function pump(): void {
    while (inFlight < concurrency) {
      const key = queue.pop();
      if (key === undefined) return;
      const request = pending.get(key);
      if (request === undefined) continue;
      request.started = true;
      inFlight += 1;
      void deps
        .requestGrid(request.id)
        .then((url) => {
          touch(key, url);
          request.settle(url);
        })
        .catch(() => {
          request.settle(null);
        })
        .finally(() => {
          inFlight -= 1;
          pending.delete(key);
          pump();
        });
    }
  }

  function get(key: string): string | null | undefined {
    if (!entries.has(key)) return undefined;
    const value = entries.get(key) ?? null;
    touch(key, value);
    return value;
  }

  function load(key: string, id: string): Promise<string | null> {
    const cached = get(key);
    if (cached !== undefined) return Promise.resolve(cached);
    const queued = pending.get(key);
    if (queued !== undefined) return queued.promise;
    let settle: (url: string | null) => void = () => {};
    const promise = new Promise<string | null>((resolve) => {
      settle = resolve;
    });
    pending.set(key, { id, promise, settle, started: false });
    queue.push(key);
    pump();
    return promise;
  }

  function dropPending(keep: ReadonlySet<string>): void {
    for (let i = queue.length - 1; i >= 0; i -= 1) {
      const key = queue[i];
      if (key === undefined || keep.has(key)) continue;
      queue.splice(i, 1);
      const request = pending.get(key);
      if (request === undefined) continue;
      pending.delete(key);
      request.settle(null);
    }
  }

  function onEvict(handler: (key: string) => void): void {
    evicted = handler;
  }

  return { get, load, dropPending, onEvict };
}
